const{getSupabase,readSession,json,readBody}=require("./_shared");const level=x=>Math.floor(Math.sqrt(Math.max(0,x)/100))+1,start=l=>(l-1)**2*100,end=l=>l**2*100;
module.exports=async(req,res)=>{const user=readSession(req);if(!user)return json(res,401,{error:"Требуется вход через Discord."});const s=getSupabase();if(!s)return json(res,503,{error:"Supabase не настроен."});await s.from("profiles").upsert({discord_id:String(user.id),username:user.username,email:user.email||null,avatar_url:user.avatar||null,banner_url:user.banner||null,is_founder:!!user.isFounder,role:user.role||"Пользователь"},{onConflict:"discord_id"});const u=new URL(req.url,"https://rynow.vercel.app"),p=u.pathname;
if(p==="/api/profile/overview"&&req.method==="GET"){const[{data:pr},{count:h},{count:f}]=await Promise.all([s.from("profiles").select("*").eq("discord_id",String(user.id)).single(),s.from("ai_history").select("*",{count:"exact",head:true}).eq("discord_id",String(user.id)),s.from("favorites").select("*",{count:"exact",head:true}).eq("discord_id",String(user.id))]);const xp=pr?.xp||0,l=level(xp);return json(res,200,{profile:pr,stats:{level:l,xp,xpCurrent:xp-start(l),xpNeeded:end(l)-start(l),questions:pr?.questions_count||0,favorites:f||0,history:h||0,aiTokens:pr?.ai_tokens_used||0,helpfulAnswers:pr?.helpful_answers||0}})}
if(p==="/api/profile/history"&&req.method==="GET"){const{data,error}=await s.from("ai_history").select("*").eq("discord_id",String(user.id)).order("created_at",{ascending:false}).limit(100);return error?json(res,500,{error:error.message}):json(res,200,{items:data})}
if(p==="/api/profile/history"&&req.method==="POST"){const b=await readBody(req);if(!b.question||!b.answer)return json(res,400,{error:"Пустые данные."});const{error}=await s.from("ai_history").insert({discord_id:String(user.id),question:String(b.question),answer:String(b.answer)});if(error)return json(res,500,{error:error.message});await s.rpc("increment_profile_activity",{p_discord_id:String(user.id),p_xp:20,p_questions:1,p_tokens:Math.ceil((String(b.question).length+String(b.answer).length)/4)});return json(res,201,{ok:true})}
if(p==="/api/profile/history"&&req.method==="DELETE"){let q=s.from("ai_history").delete().eq("discord_id",String(user.id));const id=u.searchParams.get("id");if(id)q=q.eq("id",id);const{error}=await q;return error?json(res,500,{error:error.message}):json(res,200,{ok:true})}
if(p==="/api/profile/favorites"&&req.method==="GET"){const{data,error}=await s.from("favorites").select("*").eq("discord_id",String(user.id)).order("created_at",{ascending:false}).limit(100);return error?json(res,500,{error:error.message}):json(res,200,{items:data})}
if(p==="/api/profile/favorites"&&req.method==="POST"){const b=await readBody(req);if(!b.title||!b.content)return json(res,400,{error:"Пустые данные."});const{error}=await s.from("favorites").insert({discord_id:String(user.id),title:String(b.title),content:String(b.content),source:String(b.source||"AI")});if(error)return json(res,500,{error:error.message});await s.rpc("increment_profile_activity",{p_discord_id:String(user.id),p_xp:5,p_questions:0,p_tokens:0});return json(res,201,{ok:true})}
if(p==="/api/profile/favorites"&&req.method==="DELETE"){const id=u.searchParams.get("id");const{error}=await s.from("favorites").delete().eq("discord_id",String(user.id)).eq("id",id);return error?json(res,500,{error:error.message}):json(res,200,{ok:true})}
if(p==="/api/profile/settings"&&req.method==="GET"){const{data}=await s.from("user_settings").select("*").eq("discord_id",String(user.id)).maybeSingle();return json(res,200,{settings:data||{animations:true,compact_answers:false,confirm_clear:true}})}
if(p==="/api/profile/settings"&&req.method==="PUT"){const b=await readBody(req),{data,error}=await s.from("user_settings").upsert({discord_id:String(user.id),animations:b.animations!==false,compact_answers:!!b.compactAnswers,confirm_clear:b.confirmClear!==false,updated_at:new Date().toISOString()},{onConflict:"discord_id"}).select().single();return error?json(res,500,{error:error.message}):json(res,200,{settings:data})}
json(res,404,{error:"Route not found"})};